# Generated by Django 4.0 on 2021-12-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cit', models.IntegerField()),
                ('Nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codseq', models.IntegerField()),
                ('commune_ar', models.CharField(max_length=50)),
                ('commune_fr', models.CharField(max_length=50)),
                ('code_wil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dir', models.IntegerField()),
                ('code_dir', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=150)),
                ('direction_ar', models.CharField(max_length=150)),
                ('poste_dir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dom', models.IntegerField()),
                ('domaine_ar', models.CharField(max_length=150)),
                ('domaine_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='petitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_enr', models.IntegerField(default=0)),
                ('date_declaration', models.DateTimeField()),
                ('object', models.TextField(max_length=500)),
                ('finish', models.BooleanField(default=False)),
                ('code_req', models.CharField(max_length=250)),
                ('agent', models.CharField(max_length=50)),
            ],
        ),
    ]
