# Generated by Django 4.0 on 2021-12-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitions',
            name='cit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.citoyen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petitions',
            name='com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.commune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petitions',
            name='dom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petition.domaine'),
            preserve_default=False,
        ),
    ]
